name: Ambianic Fall Detection

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    # Skip CI if the commit message includes the string '[skip ci]'
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test script
        env:
          ARCH: "linux/amd64"
          TAG_SUFFIX: "amd64"
        run: |
          pwd
          ls -al
          echo GITHUB_WORKSPACE=${GITHUB_WORKSPACE}
          echo "ARCH=${ARCH}"
          ${GITHUB_WORKSPACE}/build/ci-test-job.sh
