name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy-validate:
    name: Validate deployment on Test.PyPi.org
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
      run: |
        cp README.md src/
        cd src
        python setup.py sdist bdist_wheel
        twine upload --verbose --repository  testpypi dist/*
        # twine upload dist/*
  deploy-prod:
    name: Deploy to PyPi.org
    needs: [deploy-validate]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        cp README.md src/
        cd src
        python setup.py sdist bdist_wheel
        twine upload --verbose dist/*
        
